### ISSUE TITLE
Remove `spawn-sync`

### ISSUE THREAD

**Issue by feross** [IndigoUnited/node-cross-spawn#28]
Can we remove the `spawn-sync` dependency? Node 0.10 will be completely unsupported in about 6 months (even including security releases). It's going to be completely dead soon.

It's a huge burden to maintainers to answer users questions about the native dependency errors in the npm install output. Even though we know it's harmless output, since the dependency is optional, users don't. So, we see a lot of opened issues about this.

Here's a proposal:

- Remove `spawn-sync`, effectively dropping 0.10 support
- Publish this in a new major version. (Users that need 0.10 support can just lock to the previous version.)

Related issues:
https://github.com/IndigoUnited/node-cross-spawn/pull/18
https://github.com/websockets/ws/issues/577

**Comment by satazor** [comment]
I agree it's time to move forward. Regarding the users complaining about the errors, I think the real issue is that the output of npm is not very friendly, it definitively could be better.

`cross-spawn-async` was created to kind of mitigate this same issue, see https://github.com/IndigoUnited/node-cross-spawn/issues/19

So the plan need to include this module has well:

* [ ] Remove `spawn-sync`, effectively dropping 0.10 support
* [ ] Publish this in a new major version. (Users that need 0.10 support can just lock to the previous version.)
* [ ] Deprecate `cross-spawn-async`
* [ ] Add a visible note on the README or perhaps add a CHANGELOG so we can explain this change to users

Thoughts?

Also //cc @BigstickCarpet

**Comment by feross** [comment]
Sounds like a fine plan to me! :

**Comment by satazor** [comment]
Also //cc @ForbesLindesay

**Comment by ForbesLindesay** [comment]
I agree with this, spawn-sync is a polyfill that is rapidly going to cease to be useful/needed.  Removing the dependency and just forcing people onto a more recent version of node will certainly lessen the support burdon for me.

**Comment by satazor** [comment]
//cc @kevva @stefanpenner, whats the node support on ember cli and yo?

**Comment by satazor** [comment]
Bump

**Comment by satazor** [comment]
@feross what do you think about #31?

**Comment by feross** [comment]
@satazor Looks like a great solution.

**Comment by stefanpenner** [comment]
> //cc @kevva @stefanpenner, whats the node support on ember cli and yo?

ember-cli supports 0.10.x

**Comment by satazor** [comment]
@stefanpenner I thought it did, nvm.

I will work on this in the weekend. Thanks for the feedback.

**Comment by stefanpenner** [comment]
@satazor i believe at one point we did, but if memory serves node 0.10.x requires a native extension for execSync, which proved to be a pain point for many of our users. We now (atleast the default install) have no native extensions.

But thank you for checking in :)

**Comment by mgol** [comment]
Has there been any progress on this issue? Is some help needed? I could try to find some time to get the ball rolling on that one if others are busy.

**Comment by kevva** [comment]
@satazor, late to the party here, but `yo` is `>=0.12`.

**Comment by satazor** [comment]
I will give this a go today.

**Comment by satazor** [comment]
Done guys!

**Comment by MiracleBlue** [comment]
I believe this solution, while indeed vey nice, is causing Rollup a bunch of grief when used with the [rollup node resolve plugin](https://github.com/rollup/rollup-plugin-node-resolve).  Since spawn-sync is no longer included automatically in the dependency tree, and the conditional branch under which the require call to it is nested is not detected as being a dead branch, the rollup plugin dies when it attempts to inline the code for spawn-sync :(

Obviously, the easiest solution in my case would be to just install spawn-sync into my project's dependency tree, which I just tried and it did work up until it found another missing dynamic import within spawn-sync itself; but having never used rollup before this I ended up on a very long wild goose chase trying to figure out what config I had messed up with rollup, but I believe rollup was working exactly as it should in this case (though maybe it could do with a flag to allow skipping of inlining modules that aren't located at build time?  It does have an option to skip inlining specific modules too so that might be my short-term solution)

**Comment by ForbesLindesay** [comment]
rollup is generally best used for client side applications.  I think you will have a lot of problems trying to use it on the server side.  cross-spawn should only be used on the server side.  If we want to get this working the best bet would be to figure out a way to make rollup see this as dead code.  Either rollup needs to recognise and propagate the fact that `sync` here is always truthy on modern node versions, or it needs to offer up some other method of indicating that the module should not be bundled.

**Comment by MiracleBlue** [comment]
Ah.  I see.  I searched high and low for anything that could tell me whether or not Rollup could be used for my node CLI app, but it seemed vaguely like it could do it (based on the config options it supported) so I thought I'd give it a go.  Guess that explains why I'm having so many issues ;)

Thanks for the information, maybe I should submit an issue to Rollup to add some clarification to the docs for people like me on what *not* to do :)

**Comment by ForbesLindesay** [comment]
In general, rollup **can** be used with node apps, and **can** significantly reduce startup times.  However, there will be modules that work in node, but do not work well with rollup.  It will likely also not give you meaningful startup time improvements unless all/most of your code is using ES6 style imports.
