### ISSUE TITLE
Commands with spaces fail with shell: true

### ISSUE THREAD

**Issue by imgx64** [IndigoUnited/node-cross-spawn#77]
Commands with spaces fail with `shell: true`, but work if it's false. node developers say fixing this from their side would break other things: nodejs/node#7367 . Should this be fixed in cross-spawn? What do you think?

```
> require('cross-spawn').spawn('C:\\Program Files\\nodejs\\node.exe', [], {shell:true})
undefined
> Error: spawn C:\Program Files\nodejs\node.exe ENOENT
    at notFoundError (C:\Users\redacted\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (C:\Users\redacted\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (C:\Users\redacted\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
> require('cross-spawn').spawn('C:\\Program Files\\nodejs\\node.exe', [], {shell:false})
ChildProcess {
...
```

**Comment by imgx64** [comment]
This is a regression in 5.0.0. `cross-spawn@4.0.2` handled this correctly.

**Comment by satazor** [comment]
Sorry for the late response.

When you are using `shell: true`, you are executing code specific to the platform you are targeting. That's why there's no escape being done in the arguments. The same applies to the command itself. 

Having that said, this is by design. Basically, when you use `shell:true`, you are in charge of everything.
